package com.college.lostfound.ui;

import com.college.lostfound.dao.ClaimDAO;import com.college.lostfound.dao.ItemDAO;import com.college.lostfound.model.Claim;import com.college.lostfound.model.Item;import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;

public class AdminDashboard extends JFrame {
    final DefaultTableModel items=new DefaultTableModel(new String[]{"ID","Item","Type","Category","Location","Date","Status","Reporter"},0);final JTable itemTable=new JTable(items);final DefaultTableModel claims=new DefaultTableModel(new String[]{"Claim ID","Item ID","Item","Claimant","Description","Status"},0);final JTable claimTable=new JTable(claims);
    public AdminDashboard(){setTitle("Admin Dashboard - College Lost & Found");setSize(1050,650);setLocationRelativeTo(null);setDefaultCloseOperation(EXIT_ON_CLOSE);JTabbedPane tabs=new JTabbedPane();JPanel ip=new JPanel(new BorderLayout());ip.add(new JScrollPane(itemTable),BorderLayout.CENTER);JPanel ib=new JPanel();JButton refresh=new JButton("Refresh"),returned=new JButton("Mark Returned"),closed=new JButton("Close Item"),delete=new JButton("Delete");ib.add(refresh);ib.add(returned);ib.add(closed);ib.add(delete);ip.add(ib,BorderLayout.SOUTH);JPanel cp=new JPanel(new BorderLayout());cp.add(new JScrollPane(claimTable),BorderLayout.CENTER);JPanel cb=new JPanel();JButton approve=new JButton("Approve Claim"),reject=new JButton("Reject Claim");cb.add(approve);cb.add(reject);cp.add(cb,BorderLayout.SOUTH);tabs.add("Items",ip);tabs.add("Claims",cp);add(tabs);refresh.addActionListener(e->loadItems());returned.addActionListener(e->status("RETURNED"));closed.addActionListener(e->status("CLOSED"));delete.addActionListener(e->delete());approve.addActionListener(e->claimStatus("APPROVED"));reject.addActionListener(e->claimStatus("REJECTED"));loadItems();loadClaims();}
    void loadItems(){try{items.setRowCount(0);for(Item i:new ItemDAO().getAll())items.addRow(new Object[]{i.getItemId(),i.getItemName(),i.getType(),i.getCategoryName(),i.getLocation(),i.getItemDate(),i.getStatus(),i.getReporterName()});}catch(Exception e){error(e);}}
    void loadClaims(){try{claims.setRowCount(0);for(Claim c:new ClaimDAO().getAll())claims.addRow(new Object[]{c.getClaimId(),c.getItemId(),c.getItemName(),c.getClaimantName(),c.getClaimDescription(),c.getStatus()});}catch(Exception e){error(e);}}
    void status(String s){int r=itemTable.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Select an item.");return;}try{new ItemDAO().updateStatus((int)items.getValueAt(r,0),s);loadItems();}catch(Exception e){error(e);}}
    void delete(){int r=itemTable.getSelectedRow();if(r<0)return;try{new ItemDAO().delete((int)items.getValueAt(r,0));loadItems();}catch(Exception e){error(e);}}
    void claimStatus(String s){int r=claimTable.getSelectedRow();if(r<0){JOptionPane.showMessageDialog(this,"Select a claim.");return;}try{new ClaimDAO().updateClaim((int)claims.getValueAt(r,0),s);loadClaims();loadItems();}catch(Exception e){error(e);}}
    void error(Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);}
}
