package com.college.lostfound.ui;

import com.college.lostfound.dao.ItemDAO;import com.college.lostfound.model.Item;import com.college.lostfound.model.User;import javax.swing.*;import java.awt.*;import java.time.LocalDate;

public class ReportItemFrame extends JFrame {
    JTextField name=new JTextField(),location=new JTextField(),date=new JTextField(LocalDate.now().toString()),contact=new JTextField();JTextArea desc=new JTextArea(4,20);JComboBox<String> category=new JComboBox<>();final User user;final String type;
    public ReportItemFrame(User user,String type){this.user=user;this.type=type;setTitle("Report "+type+" Item");setSize(500,500);setLocationRelativeTo(null);setDefaultCloseOperation(DISPOSE_ON_CLOSE);try{for(String c:new ItemDAO().getCategories())category.addItem(c);}catch(Exception e){JOptionPane.showMessageDialog(this,"Could not load categories: "+e.getMessage());}JPanel p=new JPanel(new GridLayout(7,2,8,8));p.setBorder(BorderFactory.createEmptyBorder(20,20,20,20));p.add(new JLabel("Item Name"));p.add(name);p.add(new JLabel("Category"));p.add(category);p.add(new JLabel("Location"));p.add(location);p.add(new JLabel("Date (YYYY-MM-DD)"));p.add(date);p.add(new JLabel("Description"));p.add(new JScrollPane(desc));p.add(new JLabel("Contact"));p.add(contact);JButton submit=new JButton("Submit Report");p.add(submit);add(p);submit.addActionListener(e->submit());}
    void submit(){try{if(name.getText().isBlank()||location.getText().isBlank()){JOptionPane.showMessageDialog(this,"Item name and location are required.");return;}Item i=new Item();i.setUserId(user.getUserId());i.setCategoryId(new ItemDAO().getCategoryId((String)category.getSelectedItem()));i.setItemName(name.getText().trim());i.setDescription(desc.getText().trim());i.setLocation(location.getText().trim());i.setItemDate(LocalDate.parse(date.getText().trim()));i.setType(type);i.setContactInfo(contact.getText().trim());if(new ItemDAO().addItem(i)){JOptionPane.showMessageDialog(this,"Item report submitted successfully.");dispose();}}catch(Exception ex){JOptionPane.showMessageDialog(this,"Could not submit report: "+ex.getMessage());}}
}
