package com.college.lostfound.ui;

import com.college.lostfound.dao.ItemDAO;import com.college.lostfound.model.Item;import com.college.lostfound.model.User;import javax.swing.*;import javax.swing.table.DefaultTableModel;import java.awt.*;

public class SearchItemsFrame extends JFrame {
    final User user;final String type;final JTextField keyword=new JTextField();final DefaultTableModel model=new DefaultTableModel(new String[]{"ID","Item","Category","Location","Date","Status","Reporter"},0);final JTable table=new JTable(model);
    public SearchItemsFrame(User user,String type){this.user=user;this.type=type;setTitle("Search "+type+" Items");setSize(850,500);setLocationRelativeTo(null);setDefaultCloseOperation(DISPOSE_ON_CLOSE);JPanel top=new JPanel(new BorderLayout(8,8));top.add(new JLabel("Search by name/location/description:"),BorderLayout.WEST);top.add(keyword,BorderLayout.CENTER);JButton search=new JButton("Search");top.add(search,BorderLayout.EAST);add(top,BorderLayout.NORTH);add(new JScrollPane(table),BorderLayout.CENTER);JButton claim=new JButton("Claim Selected Item");add(claim,BorderLayout.SOUTH);search.addActionListener(e->load());claim.addActionListener(e->claim());load();}
    void load(){try{model.setRowCount(0);for(Item i:new ItemDAO().search(type,keyword.getText()))model.addRow(new Object[]{i.getItemId(),i.getItemName(),i.getCategoryName(),i.getLocation(),i.getItemDate(),i.getStatus(),i.getReporterName()});}catch(Exception e){JOptionPane.showMessageDialog(this,"Search error: "+e.getMessage());}}
    void claim(){int row=table.getSelectedRow();if(row<0){JOptionPane.showMessageDialog(this,"Select an item first.");return;}if("LOST".equals(type)){JOptionPane.showMessageDialog(this,"Claims are intended for FOUND items.");return;}int itemId=(int)model.getValueAt(row,0);String text=JOptionPane.showInputDialog(this,"Why do you believe this item belongs to you?");if(text!=null&&!text.isBlank())try{if(new com.college.lostfound.dao.ClaimDAO().addClaim(itemId,user.getUserId(),text)){JOptionPane.showMessageDialog(this,"Claim submitted for admin verification.");load();}}catch(Exception e){JOptionPane.showMessageDialog(this,"Claim error: "+e.getMessage());}}
}
